
// Stable copy of the XAML-generated MainWindow template body.
// The generated .g.hpp is not reliably emitted in this checkout.
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

namespace winrt::AsusFanControlNative::implementation
{


    using Application = ::winrt::Microsoft::UI::Xaml::Application;
    using ComponentResourceLocation = ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    using DataTemplate = ::winrt::Microsoft::UI::Xaml::DataTemplate;
    using DependencyObject = ::winrt::Microsoft::UI::Xaml::DependencyObject;
    using DependencyProperty = ::winrt::Microsoft::UI::Xaml::DependencyProperty;
    using IComponentConnector = ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector;
    using Uri = ::winrt::Windows::Foundation::Uri;
    using XamlBindingHelper = ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper;

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///MainWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
        }
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::Connect(int32_t connectionId, IInspectable const& target)
    {
        switch (connectionId)
        {
        case 2:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->ErrorBanner(targetElement);
            }
            break;
        case 3:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->TurnOffOnExitToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->TurnOffOnExit_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 4:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->SafeClampToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SafeClamp_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 5:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->LiveApplyToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->LiveApply_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 6:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->MinimizeToTrayToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->MinimizeToTray_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 7:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->AutoRefreshToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->AutoRefresh_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 8:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->FanSpeedsValue(targetElement);
            }
            break;
        case 9:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->FanCountValue(targetElement);
            }
            break;
        case 10:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->CpuTempValue(targetElement);
            }
            break;
        case 11:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->PresetButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 12:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->PresetButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 13:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->PresetButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 14:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->PresetButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 15:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Slider>();
                this->SpeedSlider(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SpeedSlider_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 16:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->RequestedSpeedValue(targetElement);
            }
            break;
        case 17:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->ErrorTitleText(targetElement);
            }
            break;
        case 18:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->ErrorDetailText(targetElement);
            }
            break;
        case 19:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->RefreshClicked(p0, p1);
                    }
                });
            }
            break;
        case 20:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                this->ApplyButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ApplyClicked(p0, p1);
                    }
                });
            }
            break;
        case 21:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                this->DiscardButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->DiscardClicked(p0, p1);
                    }
                });
            }
            break;
        case 22:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ExitClicked(p0, p1);
                    }
                });
            }
            break;
        case 23:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->StatusSubtitle(targetElement);
            }
            break;
        case 24:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->HardwareStateBadge(targetElement);
            }
            break;
        case 25:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->SessionStateBadge(targetElement);
            }
            break;
        case 26:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->PendingStateBadge(targetElement);
            }
            break;
        case 27:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->LastRefreshText(targetElement);
            }
            break;
        }
        _contentLoaded = true;
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects to disconnect." };
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::UnloadObject(DependencyObject const&)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects." };
    }


    template <typename D, typename... I>
    IComponentConnector MainWindowT<D, I...>::GetBindingConnector(int32_t, IInspectable const&)
    {
        return nullptr;
    }

    template struct MainWindowT<struct MainWindow>;
}


#pragma warning(pop)


